# 쿼리 설정 파일
# DB 연결 정보는 .env 파일에서 관리합니다

query:

  # categories_name:
  #   - "pants"
  # categories:
  #   - "데님 팬츠"
  #   - "코튼 팬츠"
  #   - "슬랙스"
  #   - "숏 팬츠"
  #   - "트레이닝 팬츠"
  

  # categories_name:
  #   - "outer"
  # categories:  
  #   - "가디건"
  #   - "자켓"
  #   - "코트"
  #   - "바람막이, 져지"
  #   - "패딩"
  #   - "베스트"

  # categories_name:
  #   - "shirts"
  # categories:
  #   - "맨투맨, 후드"
  #   - "니트"
  #   - "블라우스, 셔츠"
  #   - "반팔 티셔츠"
  #   - "긴팔 티셔츠"
  #   - "민소매"

  categories_name:
    - "outerandshirts"
  categories:  
    - "가디건"
    - "자켓"
    - "코트"
    - "바람막이, 져지"
    - "패딩"
    - "베스트"
    - "맨투맨, 후드"
    - "니트"
    - "블라우스, 셔츠"
    - "반팔 티셔츠"
    - "긴팔 티셔츠"
    - "민소매"

  # categories_name:
  #   - "onepiece"
  # categories:
  #   - "미니 원피스"
  #   - "미디 원피스"
  #   - "롱 원피스"
  #   - "점프수트"
  
  # categories_name:
  #   - "skirts"
  # categories:
  #   - "미니 스커트"
  #   - "미디 스커트"
  #   - "롱 스커트"
  
  
    # === 액세서리 ===
    # - "모자"
    # - "머플러"
    # - "장갑"
    # === 가방 ===
    # - "백팩"
    # - "숄더백, 토트백"
    # - "에코백"
    # - "지갑"
    # === 기타 ===
    # - "셋업"
    # - "신발"
  
  # 날짜 필터 (이 날짜 이후의 데이터만)
  date_from: "2025-10-10"
  
  # member_id 필터
  member_ids: [2, 3]
  
  # 최대 개수 (null이면 전체)
  limit: null
